version: "3"

services:
  db:
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    restart: always
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: masterpassword
      MYSQL_DATABASE: database
      MYSQL_USER: root
    ports:
      - 3306:3306

  client:
    command: "yarn start"
    depends_on:
      - server
    networks:
      - webnet
    build: ./client
    volumes:
      - ./client:/project
    ports:
      - 3000:3000
    environment:
      SERVER: http://localhost:1337

  server:
    depends_on:
      - db
    build: ./server
    networks:
      - webnet
    volumes:
      - ./server:/project
    links:
      - db
    ports:
      - 1337:1337
    environment:
      PORT: 1337
      DB_DATABASE: database
      DB_USER: root
      DB_PASSWORD: masterpassword
      DB_HOST: db
      DB_PORT: 3306

#  nginx:
#    image: nginx
#    volumes:
#      - ./nginx/config.template:/etc/nginx/conf.d/config.template
#    ports:
#      - "1337:80"
#    networks:
#      - webnet
#    depends_on:
#      - server
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/config.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  webnet:
